{
  try {
    doRun(monitor);
  }
  finally {
    try {
      reconcile();
    }
 catch (    RuntimeException ex) {
      LOG.debug("Unexpected exception",ex);
    }
  }
}
