{
  _FunctionTypes._void_P0_E1<? extends Exception> fun=new _FunctionTypes._void_P0_E1<Exception>(){
    public void invoke() throws Exception {
      throw new Exception();
    }
  }
;
  try {
    new MPS14653_helper.Context().acceptFunction(fun);
    Assert.fail();
  }
 catch (  Exception e) {
  }
}
