{
  try {
    runnable.run();
  }
 catch (  RuntimeException unexpected) {
    LOG.error("Unexpected exception",unexpected);
  }
}
